apiVersion: apps/v1
kind: Deployment
metadata:
  name: champion-consumer
  labels:
    app: champion-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: champion-consumer
  template:
    metadata:
      labels:
        app: champion-consumer
    spec:
      containers:
      - name: champion-consumer
        image: champion-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: API_BASE_URL
          value: "http://movement-speed-api.api-cluster.svc.cluster.local"
        - name: AWS_ENDPOINT
          value: "http://localstack.consumer-cluster.svc.cluster.local:4566"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: DB_HOST
          value: "postgres.consumer-cluster.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "champions"
        - name: SYNC_INTERVAL
          value: "60"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
