version: '3.8'

services:
  movement-speed:
    build:
      context: .
      dockerfile: Dockerfile.movement-speed
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY}
    restart: on-failure
    
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY}
    ports:
      - "8080:8080"
    restart: on-failure

